[32mINFO    [0m selenium.webdriver.remote.remote_connection:remote_connection.py:117 Could not connect to port 4725 on host 127.0.0.1
[32mINFO    [0m selenium.webdriver.remote.remote_connection:remote_connection.py:136 Could not get IP address for host: 127.0.0.1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782C7AC08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782C99488>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:745 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782C99A48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session