2022-03-20 20:58:52 [INFO] Could not connect to port 4725 on host 127.0.0.1 (remote_connection.py:117)
2022-03-20 20:58:52 [INFO] Could not get IP address for host: 127.0.0.1 (remote_connection.py:136)
2022-03-20 20:58:54 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782C7AC08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:58:56 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782C99488>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:58:58 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782C99A48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:59:01 [INFO] Could not connect to port 4725 on host 127.0.0.1 (remote_connection.py:117)
2022-03-20 20:59:01 [INFO] Could not get IP address for host: 127.0.0.1 (remote_connection.py:136)
2022-03-20 20:59:03 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237830C1308>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:59:05 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237830BF088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:59:07 [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000237830BFB08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:59:10 [INFO] Could not connect to port 4725 on host 127.0.0.1 (remote_connection.py:117)
2022-03-20 20:59:10 [INFO] Could not get IP address for host: 127.0.0.1 (remote_connection.py:136)
2022-03-20 20:59:12 [WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782FF8148>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
2022-03-20 20:59:15 [WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023782E81988>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session (connectionpool.py:745)
